--Họ tên: Trần Văn Quốc Thắng
--MSSV: DH52007101
--Lớp: D20_TH11

--1/
SELECT avg(LUONG) as LuongTB
FROM NHANVIEN
WHERE LOAINV=0

--2/
SELECT avg(LUONG) as LuongTB
FROM NHANVIEN
WHERE LOAINV=1

--3/
SELECT SBDI, NGAYDI, count(*) as SL
FROM CHUYENBAY join LICHBAY on LICHBAY.MACB=CHUYENBAY.MACB
WHERE NGAYDI='11/01/2000' and SBDI='MIA'
GROUP BY SBDI, NGAYDI

--4/
SELECT SBDEN, count(*) as SL
FROM CHUYENBAY
GROUP BY SBDEN

--5/
SELECT SBDI, NGAYDI, count(*) as SL
FROM CHUYENBAY join LICHBAY on CHUYENBAY.MACB=LICHBAY.MACB
WHERE SBDI in ('MIA', 'ORD', 'SLC', 'BOS')
GROUP BY SBDI, NGAYDI

--6/
SELECT MACB, NGAYDI, count(*) SL
FROM PHANCONG join NHANVIEN on PHANCONG.MANV=NHANVIEN.MANV
WHERE LOAINV=0
GROUP BY MACB, NGAYDI

--7/
SELECT MACB, NGAYDI, count(*) SL
FROM DATCHO
GROUP BY MACB, NGAYDI

--8/
SELECT MACB, NGAYDI, sum(LUONG) as TongLuong
FROM PHANCONG join NHANVIEN on PHANCONG.MANV=NHANVIEN.MANV
WHERE LOAINV=1
GROUP BY MACB, NGAYDI

--9/
SELECT MALOAI, SBDEN, count(*) as SL
FROM CHUYENBAY join LICHBAY on CHUYENBAY.MACB=LICHBAY.MACB
WHERE SBDEN='ORD'
GROUP BY MALOAI, SBDEN

--10/
SELECT SBDI, count(*) as SL
FROM CHUYENBAY
WHERE datepart(hh, GIODI) between 10 and 22
GROUP BY SBDI
HAVING count(*) > 2

--11/
SELECT TEN, NGAYDI, count(*) as SL
FROM NHANVIEN join PHANCONG on NHANVIEN.MANV=PHANCONG.MANV
GROUP BY TEN, NGAYDI
HAVING count(*) >= 2

--12/
SELECT MACB, NGAYDI, count(MAKH) as SL
FROM DATCHO
GROUP BY MACB, NGAYDI
HAVING count(MAKH) < 3

--13/
SELECT SOHIEU, MALOAI, count(*) as SL
FROM LICHBAY join PHANCONG on LICHBAY.MACB=PHANCONG.MACB
	join NHANVIEN on PHANCONG.MANV=NHANVIEN.MANV
WHERE NHANVIEN.MANV='1001' and LOAINV=1
GROUP BY SOHIEU, MALOAI
HAVING COUNT(*) > 2

--14/
SELECT HANGSX, count(*) as SL
FROM LOAIMB
GROUP BY HANGSX

--15/
SELECT SBDI, count(*) as SL
FROM CHUYENBAY join LICHBAY on CHUYENBAY.MACB=LICHBAY.MACB
WHERE datepart(qq,NGAYDI)=4
GROUP BY SBDI
HAVING count(*) > 2
ORDER BY count(*) desc